# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: edange
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: node-express-serverless
# "service" is the name of this project. This will also be added to your AWS resource names.
service: node-express-serverless

provider:
  name: aws
  runtime: nodejs20.x

functions:
  api:
    handler: src/server.handler
    timeout: 60
    events:
      - httpApi: "*"

plugins:
  - serverless-offline
